Error handling in L6 scripts
   - Add error handling in restore script.
   - Add error handling in backup script.

diff --git a/scripts/backup b/scripts/backup
--- a/scripts/backup
+++ b/scripts/backup
@@ -7,5 +7,19 @@ OUT_FILE="$OUT_FILE_NAME-$VERSION.tar"
 
 # take the dump
 mongodump -d $DB_NAME
+if [ $? -ne 0 ]; then
+  echo "Error: Something went wrong while taking db dump."
+  echo "Aborting backup."
+  exit 1;
+fi
+
 # tar the dump/$DB_NAME folder
 tar cfvz $OUT_FILE ./dump/$DB_NAME
+if [ $? -ne 0 ]; then
+  echo "Error: Something went wrong while tar-ing the dump."
+  echo "Aborting backup."
+  exit 1;
+fi
+
+echo "Backup successful."
+exit 0;
diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -3,9 +3,38 @@
 DB_NAME="ovpl"
 VERSION="v1.0.4"
 
-$BACKUP_FILE=$1
+BACKUP_FILE=$1
 
-# untar the $OUT_FILE file
-tar xfvz $1
-# take the dump
+usage() {
+  echo "Usage:"
+  echo "$0 <path/to/the/backup/file.tar>"
+}
+
+if [ -z $BACKUP_FILE ]; then
+  echo "Error: No arguments were passed!!"
+  echo "Error: The path to the backup file must be passed."
+  usage
+  exit 1;
+fi
+
+# untar the $BACKUP_FILEfile
+tar xfvz $BACKUP_FILE
+if [ $? -ne 0 ]; then
+  echo "Error: Something went wrong while untaring."
+  echo "Aborting restore."
+  exit 1;
+fi
+
+# restore from the dump folder
 mongorestore -d $DB_NAME dump/$DB_NAME
+if [ $? -ne 0 ]; then
+  echo "Error: Something went wrong while restoring db dump."
+  echo "Aborting restore."
+  exit 1;
+fi
+
+# cleanup
+rm -rf ./dump
+
+echo "Restore successful."
+exit 0;
